export { StockError, type StockErrorCode } from './errors';
export {
  assertOutletInFranchise,
  assertWarehouseAccess,
  ensureStockAllowed,
  stockActorHas,
  stockCapabilities,
  stockContextForActor,
  stockSystemActor,
  type StockActor,
} from './authorize';
export { recordStockAudit, stockAuditOutOfBand, type StockAuditInput } from './audit';
export {
  canonicalJson,
  signEventPayload,
  verifyEventSignature,
  ingestInboundEvent,
  recordStockOutbox,
  type IngestResult,
  type StockOutboxInput,
} from './events';
export {
  resolveStockActor,
  upsertIdentityProjection,
  type VerifiedIdentity,
  type UpsertProjectionCommand,
} from './identity-projection';
export { toBaseQuantity } from './units';
export { applyInbound, applyOutbound, positionValuePaise, type AvgState } from './valuation';
export {
  orderFefo,
  allocateFefo,
  type BatchPosition,
  type Allocation,
  type FefoResult,
} from './fefo';
export {
  postMovement,
  postMovements,
  pickFefo,
  rebuildProjections,
  type MovementInput,
  type MovementResult,
  type FefoPick,
} from './ledger';
export {
  createItem,
  setItemUnitConversion,
  addItemBarcode,
  createWarehouse,
  configureOutletStock,
  createBatch,
  listItems,
  getItemBalances,
  type CreateItemCommand,
  type CreateWarehouseCommand,
  type ConfigureOutletStockCommand,
  type CreateBatchCommand,
  type ItemRow,
  type BalanceRow,
} from './inventory';
export { buildLabelPayload, type LabelInput, type LabelPayload } from './labels';
export {
  scalePerServing,
  scalingPreview,
  assertRecipePublished,
  createRecipe,
  publishRecipeVersion,
  getPublishedRecipe,
  type ScalingPreview,
  type PublishedRecipeRef,
  type CreateRecipeCommand,
  type RecipeComponentInput,
  type PublishRecipeVersionCommand,
  type PublishedRecipe,
} from './recipes';
export { processSaleCompleted, processSaleRefunded, type ProcessResult } from './consumption';
export {
  enqueueOfflineDraft,
  syncOfflineDrafts,
  isStockFeatureEnabled,
  setStockFeatureFlag,
  type OfflineDraftKind,
  type EnqueueOfflineDraftCommand,
  type SyncOfflineResult,
} from './offline';
export {
  deliverBillingEventsToStock,
  processStockInbox,
  reconcileCrossSystem,
  type ReconciliationReport,
} from './relay';
export {
  getIntegrationHealth,
  retryInboxDeadLetter,
  type IntegrationHealth,
  type DeadLetter,
} from './integration-health';
export {
  draftRecall,
  activateRecall,
  quarantineRecallLocation,
  acknowledgeRecallLocation,
  closeRecall,
  getRecall,
  type DraftRecallCommand,
  type ActivateRecallResult,
  type RecallSummary,
} from './recall';
export {
  suggestReorderQty,
  rebuildDailyConsumptionRollups,
  generateReorderSuggestions,
  listReorderSuggestions,
  dismissSuggestion,
  flagAnomaly,
  getOwnerDashboard,
  getCentralOversight,
  type SuggestionInputs,
  type SuggestionRow,
  type GenerateSuggestionsCommand,
  type FlagAnomalyCommand,
  type OwnerDashboard,
  type CentralOversight,
} from './analytics';
export {
  recordLocalInward,
  reviewLocalInward,
  type RecordLocalInwardCommand,
  type ReviewLocalInwardCommand,
} from './local-inward';
export {
  signCheckout,
  signWebhook,
  stubRazorpayGateway,
  httpRazorpayGateway,
  resolveRazorpayGateway,
  type RazorpayGateway,
  type RazorpayOrder,
  type RazorpayPayment,
} from './razorpay';
export {
  upsertDeliveryRule,
  publishCatalogItem,
  getSupplyCatalogForOutlet,
  type UpsertDeliveryRuleCommand,
  type PublishCatalogItemCommand,
  type CatalogEntry,
} from './supply-catalog';
export {
  buildGstInvoice,
  approveStockOrder,
  allocateStockOrder,
  dispatchStockOrder,
  recordOutletInward,
  resolveDiscrepancy,
  getDispatch,
  type GstInvoice,
  type GstInvoiceLine,
  type AllocateResult,
  type DispatchResult,
  type RecordOutletInwardCommand,
  type OutletInwardLineInput,
  type ResolveDiscrepancyOptions,
} from './dispatch';
export {
  computeDeliveryPaise,
  createStockOrder,
  submitStockOrderForPayment,
  confirmCheckoutCallback,
  reconcileStockOrderPayment,
  handleRazorpayWebhook,
  getStockOrder,
  type CreateStockOrderCommand,
  type StockOrderLineInput,
  type StockOrderTotals,
  type CheckoutCallbackCommand,
  type RazorpayWebhookInput,
  type StockOrderView,
} from './stock-orders';
export {
  createProductionOrder,
  issueProductionMaterials,
  recordProductionOutput,
  postProduction,
  openStockCount,
  enterCountLine,
  submitCountForReview,
  approveCountAdjustments,
  recordWastage,
  createTransfer,
  dispatchTransfer,
  receiveTransfer,
  recordLabelJob,
  reverseDocument,
  type CreateProductionOrderCommand,
  type ProductionInputRequest,
  type RecordProductionOutputCommand,
  type OpenStockCountCommand,
  type CountLineInput,
  type RecordWastageCommand,
  type CreateTransferCommand,
  type TransferLineInput,
  type TransferReceiptInput,
  type RecordLabelJobCommand,
  type ReverseDocumentCommand,
} from './warehouse-ops';
export {
  listWarehouses,
  listSuppliers,
  listRecipes,
  listRecalls,
  listOrdersForFulfilment,
  getPurchaseOrder,
  type WarehouseRow,
  type SupplierRow,
  type RecipeRow,
  type RecallRow,
  type FulfilmentOrderRow,
  type PurchaseOrderDetail,
} from './reads';
export {
  createSupplier,
  approveSupplier,
  createPurchaseOrder,
  transitionPurchaseOrder,
  receiveSupplierShipment,
  createSupplierInvoice,
  recordSupplierPayment,
  getSupplierInvoice,
  initiateSupplierReturn,
  confirmSupplierReturnDispatch,
  resolveSupplierReturn,
  listPurchaseOrders,
  type CreateSupplierCommand,
  type CreatePurchaseOrderCommand,
  type PurchaseOrderLineInput,
  type ReceiveShipmentCommand,
  type ReceiveShipmentResult,
  type ReceiptLineInput,
  type CreateSupplierInvoiceCommand,
  type RecordSupplierPaymentCommand,
  type InitiateSupplierReturnCommand,
} from './procurement';
