import { z } from 'zod';

/** Security/financial audit actions (`advanced-login.md`, `billing-data-api-plan.md` §9). */
export const auditActionSchema = z.enum([
  'login.succeeded',
  'login.failed',
  'logout',
  'logout_all',
  'session.revoked',
  'otp.sent',
  'otp.verify_failed',
  'invitation.created',
  'invitation.delivered',
  'invitation.accepted',
  'invitation.expired',
  'invitation.cancelled',
  'invitation.resent',
  'account.created',
  'account.status_changed',
  'membership.changed',
  'workspace.selected',
  'franchise.created',
  'outlet.created',
  'outlet.activated',
  'outlet.suspended',
  'outlet.closed',
  'outlet.reactivated',
  'outlet.config_changed',
  'employee.created',
  'employee.updated',
  'employee.status_changed',
  'pin.set',
  'pin.reset',
  'pin.login_failed',
  'pin.locked',
  'terminal.activation_code_issued',
  'terminal.enrolled',
  'terminal.replaced',
  'terminal.locked',
  'terminal.unlocked',
  'terminal.revoked',
  'operator.locked',
  'operator.logout',
  'step_up.required',
  'disabled_account.access_attempt',
  'catalog.item_created',
  'catalog.item_updated',
  'catalog.item_override_set',
  'catalog.item_promoted',
  'catalog.item_paused',
  'catalog.recipe_linked',
  'catalog.tax_profile_created',
  'catalog.tax_profile_updated',
  'menu.publication_created',
  'menu.publication_applied',
  'menu.publication_failed',
  'shift.started',
  'shift.ended',
  'shift.force_closed',
  'cash_session.opened',
  'cash_session.closed',
  'cash_session.force_closed',
  'sale.created',
  'sale.refunded',
  'offline_auth.issued',
  'receipt_block.reserved',
  'receipt_numbers.voided',
  'sync.batch_processed',
  'bill.print_attempted',
  'attendance.checked_in',
  'attendance.checked_out',
  'attendance.corrected',
  'attendance.schedule_set',
  'expense.recorded',
  'expense.reviewed',
  'expense.reversed',
  'expense.category_created',
  'expense.threshold_set',
  'offer.created',
  'offer.published',
  'offer.paused',
  'import.previewed',
  'import.processed',
  'billing.export.created',
]);
export type AuditAction = z.infer<typeof auditActionSchema>;

export const auditResultSchema = z.enum(['success', 'failure', 'denied']);
export type AuditResult = z.infer<typeof auditResultSchema>;

export const auditEventSchema = z.object({
  id: z.uuid(),
  action: auditActionSchema,
  result: auditResultSchema,
  occurredAt: z.iso.datetime(),
  actorAccountId: z.uuid().optional(),
  actorEmployeeId: z.uuid().optional(),
  subjectId: z.uuid().optional(),
  organizationId: z.uuid().optional(),
  franchiseId: z.uuid().optional(),
  outletId: z.uuid().optional(),
  sessionId: z.uuid().optional(),
  terminalId: z.uuid().optional(),
  correlationId: z.uuid(),
  metadata: z.record(z.string(), z.unknown()).default({}),
});
export type AuditEvent = z.infer<typeof auditEventSchema>;
