-- Stock — development reset.
-- Clears all operational and integration-test rows, keeps reference data
-- (capabilities, role_capabilities, schema_migrations, units, feature_flags).
-- Never run against production.

begin;

truncate
  stock_inbox.events,
  stock_outbox.events,
  stock_audit.events,
  stock.anomaly_flags,
  stock.batches,
  stock.count_adjustment_approvals,
  stock.credit_notes,
  stock.daily_consumption_rollups,
  stock.delivery_charge_rules,
  stock.document_reversals,
  stock.identity_projection,
  stock.item_barcodes,
  stock.item_unit_conversions,
  stock.item_valuation,
  stock.items,
  stock.label_jobs,
  stock.local_inwards,
  stock.negative_stock_exceptions,
  stock.offline_drafts,
  stock.outlet_inward_lines,
  stock.outlet_inwards,
  stock.outlet_stock_settings,
  stock.prepared_batches,
  stock.production_inputs,
  stock.production_orders,
  stock.production_outputs,
  stock.purchase_order_lines,
  stock.purchase_orders,
  stock.razorpay_webhook_events,
  stock.recall_locations,
  stock.recalls,
  stock.recipe_components,
  stock.recipe_versions,
  stock.recipes,
  stock.reconciliation_runs,
  stock.reorder_suggestions,
  stock.sale_consumption_lines,
  stock.sale_consumptions,
  stock.stock_balances,
  stock.stock_count_lines,
  stock.stock_counts,
  stock.stock_dispatch_lines,
  stock.stock_dispatches,
  stock.stock_locations,
  stock.stock_movements,
  stock.stock_order_allocations,
  stock.stock_order_discrepancies,
  stock.stock_order_lines,
  stock.stock_order_payments,
  stock.stock_orders,
  stock.stock_transfer_lines,
  stock.stock_transfers,
  stock.supplier_invoices,
  stock.supplier_payments,
  stock.supplier_receipt_lines,
  stock.supplier_receipts,
  stock.supplier_returns,
  stock.suppliers,
  stock.supply_catalog_items,
  stock.supply_catalog_outlet_blocks,
  stock.warehouse_assignments,
  stock.warehouses,
  stock.wastage_events
  restart identity cascade;

commit;
